# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
permissions:
  contents: write
env:
  REPORT_HOST: "https://ravighodasara.github.io/RepoCompare/reports/" #"https://nci-ctrp.github.io/nci-accrual-rest-assured-api/reports/"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Show Current UTC Time
      shell: bash
      run: |
        echo "Current UTC time is $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        date_str=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
        echo $date_str
        echo "date_str=$date_str" >> $GITHUB_ENV

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Check Report
      id: check_report
      shell: bash
      run: |
        if test -f target/test.html; then
          echo "File Exist"
          echo "file_present=true" >> $GITHUB_OUTPUT
        else
          echo "File Not Exist"
          echo "file_present=false" >> $GITHUB_OUTPUT
        fi

    - name: Checkout report repo
      if: steps.check_report.outputs.file_present == 'true'
      uses: actions/checkout@v4
      with:
        ref: report
        path: report_repo
        
    - name: Copy Report
      id: copy_report
      if: steps.check_report.outputs.file_present == 'true'
      shell: bash
      run: |
        ls -ltr
        if [ ! -d report_repo/report ]; then
          echo "report does not exist."
          mkdir report_repo/report;
        fi
        
        echo $date_str
        mv target/test.html report_repo/report/report_$date_str.html
        cd report_repo
        git config --global user.name "RaviGhodasara"
        git config --global user.email "ravindra.ghodasara@gmail.com"
        git add report/report_$date_str.html
        git commit -m 'Report'
        ls -ltr
        git push
        SUMMARY=$'# Test Report Link\n##'
        SUMMARY_FINAL=$SUMMARY$REPORT_HOST$report_$date_str.html
        echo "$SUMMARY_FINAL" >> $GITHUB_STEP_SUMMARY
        
        
